= Glossary

== BGM

Short for _Background Music_

== CDN

Short for _Content Delivery Network_. 
This service distributes DLC across geographically-dispersed servers to make downloading files faster.

== DLC

Short for _Downloadble Content_.
DLC in TPA includes:

* Table downloads.
* Ball packs.
* Pro Mode unlocks.

== FAM

Short for _Farsight Audio Mixer_. This is the bespoke audio engine FarSight Studios uses for The Pinball Arcade.

== FPS

Short for _Frames Per Second_.
TPA requires a constant FPS to maintain accurate physics calculations.

== GPS

The abbreviation for Google's player progress tracking system called _Google Play Games Services_. 
The service provides developers a method to find, keep, and match players for mobile and web games.

== GPU

Short for _Graphics Processing Unit_.

== HID

Short for _Human Interface Device_.

== High LOD

Short for _High Level of Detail_.
Relates to the number of polygons used to construct graphical assets in the game.

== L1 

The top left digital shoulder button on controllers.

== L2

The bottom left analog shoulder button on controllers.

== LS

Left analog stick on controllers.

== Mode A

HID mode used by Moga Pocket and 3rd Party controllers.

== Mode B 

HID mode used by Moga Pro controllers only.

== R1

The top right digital shoulder button on controllers.

== R2

The bottom right analog shoulder button on controllers.

== RES

Short for _resource files_. 
Resource files contain compiled graphics and sound assets.
RES files are downloaded during DLC updates.

== RS

Right analog stick on controllers.

== SFX

Short for _Sound Effects_.

== Type A, Type B

TPA controller scheme setting, available within the in-game table menu. 

Switch between modes to switch the assigned flipper and magnasave shoulder buttons.

== TPA

Short for _The Pinball Arcade_.

== UI

Short for _User Interface_.

